---
# tasks file for ansible_galaxy_role_customize_shell_prompt

- name: "Customize shell prompt | copy file"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  copy:
    src: "{{ customize.file.name }}"
    dest: "{{ customize.file.dest_path }}"

- name: "Customize shell prompt | set customize settings"
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: |
      # 一般ユーザー
      cat "{{ shell.rc.file.path }}" | grep ". {{ customize.file.dest_path }}" >/dev/null
      if [ $? -ne 0 ]; then
          echo -n "\n" >> "{{ shell.rc.file.path }}"
          echo ". {{ customize.file.dest_path }}" >> "{{ shell.rc.file.path }}"
      fi

      cat "{{ shell.rc.file.path }}" | grep "export PS1=" >/dev/null
      if [ $? -ne 0 ]; then
          echo "export PS1=\"\[\e[1;32m\]\u@\h \[\e[36m\]\D{%y/%m/%d %H:%M:%S}\[\e[0m\]\$PS1_GIT_BRANCH \w"'\\n'"\\$ \"" >> "{{ shell.rc.file.path }}"
      fi

      # rootユーザー
      sudo cat "{{ shell.rc.root.user.file.path }}" | grep ". {{ customize.file.dest_path }}" >/dev/null
      if [ $? -ne 0 ]; then
          echo -n "\n" | sudo tee -a "{{ shell.rc.root.user.file.path }}" >/dev/null
          echo ". {{ customize.file.dest_path }}" | sudo tee -a "{{ shell.rc.root.user.file.path }}" >/dev/null
      fi

      sudo cat "{{ shell.rc.root.user.file.path }}" | grep "export PS1=" >/dev/null
      if [ $? -ne 0 ]; then
          echo "export PS1=\"\[\e[1;31m\]\u@\h \[\e[36m\]\D{%y/%m/%d %H:%M:%S}\[\e[0m\]\$PS1_GIT_BRANCH \w"'\\n'"# \"" | sudo tee -a "{{ shell.rc.root.user.file.path }}" >/dev/null
      fi
